name: Blob storage website CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run build
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.38.0
        inlineScript: |
            az storage blob upload-batch --account-name maputnik --auth-mode key -d '$web' -s ./build/build
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.38.0
        inlineScript: |
            az network front-door purge-endpoint --content-paths index.html --name maputnik-cdn --resource-group maputnik
    - name: logout
      run: |
          az logout
      if: always()
